server.port=${PORT:8080}

spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/scm_zalau_volei?allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:L6onardo2004}

spring.jpa.database-platform=${HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:create-drop}

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true